name: Build ImmortalWrt Image (Image Builder with uci stub)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGEBUILDER_VERSION: "24.10.2" # 如需其它版本请修改
      IMAGEBUILDER_ARCH: "x86-64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare variables
        run: |
          echo "IMAGEBUILDER_VERSION=${IMAGEBUILDER_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_DIR=$GITHUB_WORKSPACE/imagebuilder" >> $GITHUB_ENV

      - name: Download Image Builder (try GitHub release then OpenWrt mirror)
        run: |
          set -euo pipefail
          V=${IMAGEBUILDER_VERSION}
          TARBALL="immortalwrt-imagebuilder-${V}-x86-64.Linux-x86_64.tar.xz"
          URL1="https://github.com/immortalwrt/immortalwrt/releases/download/v${V}/${TARBALL}"
          URL2="https://downloads.openwrt.org/releases/${V}/targets/x86/64/${TARBALL}"
          echo "Trying download from $URL1"
          if ! curl -fL -o imagebuilder.tar.xz "$URL1"; then
            echo "fallback to $URL2"
            curl -fL -o imagebuilder.tar.xz "$URL2"
          fi
          mkdir -p "$IMAGE_DIR"
          tar -xJf imagebuilder.tar.xz -C "$IMAGE_DIR" --strip-components=1
          ls -la "$IMAGE_DIR"

      - name: Create uci stub (prevents 'uci: command not found' during enable)
        run: |
          sudo tee /usr/local/bin/uci > /dev/null <<'EOF'
          #!/bin/sh
          # uci stub for Image Builder / CI runs:
          # Most init scripts only check for uci presence or run simple get/set during 'enable';
          # this stub always returns success and returns empty on queries.
          case "$1" in
            get|show|export|changes|revert)
              # emulate empty output (exit 0)
              exit 0
              ;;
            set|add|delete|commit|batch)
              # pretend success for write operations during build
              exit 0
              ;;
            *)
              # default: exit success
              exit 0
              ;;
          esac
          EOF
          sudo chmod +x /usr/local/bin/uci
      - name: Ensure stub is in PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: (Optional) Show problematic init scripts for debugging
        run: |
          # 如果想调试哪些 init.d 调用了 uci，可在这里列出
          grep -R --line-number --word-regexp 'uci' $GITHUB_WORKSPACE || true

      - name: Build image (run Image Builder)
        working-directory: ${{ env.IMAGE_DIR }}
        env:
          # 如需使用仓库中的 overlay 文件夹（例如 files/），将 FILES 指向仓库路径
          FILES: "${{ github.workspace }}/files"
        run: |
          set -euo pipefail
          # 根据需要修改 PACKAGES、PROFILE、IMAGE_NAME 等
          # 示例：构建 x86-64，包含 luci、dropbear、firewall 等。请按需修改 PACKAGES。
          make image PROFILE=x86-64 PACKAGES="luci-ssl dropbear firewall" FILES="$FILES" -j$(nproc)

      - name: Upload built images
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-images
          path: ${{ env.IMAGE_DIR }}/bin/targets